const List = () => {
  return (
    <div>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
      <ul>
        <li>リスト</li>
        <li>リスト</li>
        <li>リスト</li>
      </ul>
    </div>
  );
};

export default List;
